source 'https://rubygems.org'

gem 'rake'
gem 'motion-addressbook'
gem 'motion-kit'
gem 'map-kit-wrapper'
gem 'sugarcube', :require => 'sugarcube-all'
gem 'psych'
gem 'afmotion'
gem 'awesome_print_motion'
